"""
Schematika Electrical — IEC 60617 electrical schematic diagram API.
"""

# system.system must be imported first — pre-loads layout.layout, breaking the
# circular import chain that would otherwise form via builder.py → layout.layout.
from .system.system import Circuit, add_symbol, merge_circuits, render_system  # noqa: E402
from .layout.layout import auto_connect
from .layout.wire_labels import add_wire_labels_to_circuit
from .builder import (
    BuildResult,
    CircuitBuilder,
    ComponentRef,
    PortRef,
    merge_build_results,
)
from .builder_models import merge_reuse_tags
from .descriptors import build_from_descriptors, comp, ref, term
from .exceptions import (
    CircuitValidationError,
    ComponentNotFoundError,
    PortNotFoundError,
    TagReuseError,
    TerminalReuseError,
    WireLabelMismatchError,
)

# Internal device metadata
from .internal_device import InternalDevice
from .field_devices import (
    CableData,
    ConnectionRow,
    ConnectorData,
    DeviceCable,
    DeviceEntry,
    DeviceTemplate,
    FieldDevice,
    FixedPin,
    PinDef,
    PrefixedPin,
    SequentialPin,
    generate_field_connections,
)
from .model.constants import (
    CB_2P_PINS,
    CB_3P_PINS,
    CIRCUIT_SPACING,
    CIRCUIT_SPACING_NARROW,
    CIRCUIT_SPACING_WIDE,
    COIL_PINS,
    CONTACTOR_3P_PINS,
    DEFAULT_POLE_SPACING,
    GRID_SIZE,
    NC_CONTACT_PINS,
    NO_CONTACT_PINS,
    PinPrefix,
    SPACING_COMPACT,
    SPACING_DEFAULT,
    SPACING_NARROW,
    SPACING_STANDARD,
    StandardCircuitKeys,
    StandardTags,
    THERMAL_OVERLOAD_PINS,
    WireLabels,
)
from .model.core import SymbolFactory
from .model.state import GenerationState, create_initial_state
from .plc_resolver import (
    PlcDesignation,
    PlcModuleType,
    PlcRack,
    extract_plc_connections_from_registry,
    generate_plc_report_rows,
    resolve_plc_references,
)
from schematika.project import Project
from .system.connection_registry import (
    export_registry_to_csv,
    get_registry,
    register_connection,
)
from .terminal import Terminal
from .utils.autonumbering import (
    create_autonumberer,
    get_tag_number,
    next_tag,
    next_terminal_pins,
)
from .utils.export_utils import (
    export_terminal_list,
    finalize_terminal_csv,
    merge_terminal_csv,
)
from .utils.terminal_bridges import (
    BridgeRange,
    ConnectionDef,
    expand_range_to_pins,
    generate_internal_connections_data,
    get_connection_groups_for_terminal,
    parse_terminal_pins_from_csv,
    update_csv_with_internal_connections,
)
from .utils.utils import (
    apply_start_indices,
    fixed_tag,
    get_terminal_counter,
    merge_terminals,
    natural_sort_key,
    set_tag_counter,
    set_terminal_counter,
)
from .wire import wire

# Symbol factories
from .symbols import (
    circuit_breaker_symbol,
    coil_symbol,
    contactor_symbol,
    current_transducer_assembly_symbol,
    current_transducer_symbol,
    dynamic_block_symbol,
    emergency_stop_assembly_symbol,
    emergency_stop_button_symbol,
    fuse_symbol,
    motor_symbol,
    multi_pole_spdt_symbol,
    multi_pole_terminal_symbol,
    normally_closed_symbol,
    normally_open_symbol,
    psu_symbol,
    ref_symbol,
    spdt_contact_symbol,
    terminal_box_symbol,
    terminal_symbol,
    thermal_overload_symbol,
    three_pole_circuit_breaker_symbol,
    three_pole_motor_symbol,
    three_pole_normally_closed_symbol,
    three_pole_normally_open_symbol,
    three_pole_spdt_symbol,
    three_pole_terminal_symbol,
    three_pole_thermal_overload_symbol,
    turn_switch_assembly_symbol,
    turn_switch_symbol,
    two_pole_circuit_breaker_symbol,
)

__all__ = [
    # Core
    "Circuit",
    "add_symbol",
    "merge_circuits",
    "render_system",
    "auto_connect",
    "BuildResult",
    "CircuitBuilder",
    "ComponentRef",
    "PortRef",
    "merge_reuse_tags",
    "build_from_descriptors",
    "comp",
    "ref",
    "term",
    "wire",
    "Project",
    "merge_build_results",
    "add_wire_labels_to_circuit",
    "register_connection",
    # Symbol factories
    "SymbolFactory",
    "circuit_breaker_symbol",
    "coil_symbol",
    "contactor_symbol",
    "current_transducer_assembly_symbol",
    "current_transducer_symbol",
    "dynamic_block_symbol",
    "emergency_stop_assembly_symbol",
    "emergency_stop_button_symbol",
    "fuse_symbol",
    "motor_symbol",
    "multi_pole_spdt_symbol",
    "multi_pole_terminal_symbol",
    "normally_closed_symbol",
    "normally_open_symbol",
    "psu_symbol",
    "ref_symbol",
    "spdt_contact_symbol",
    "terminal_box_symbol",
    "terminal_symbol",
    "thermal_overload_symbol",
    "three_pole_circuit_breaker_symbol",
    "three_pole_motor_symbol",
    "three_pole_normally_closed_symbol",
    "three_pole_normally_open_symbol",
    "three_pole_spdt_symbol",
    "three_pole_terminal_symbol",
    "three_pole_thermal_overload_symbol",
    "turn_switch_assembly_symbol",
    "turn_switch_symbol",
    "two_pole_circuit_breaker_symbol",
    # Constants
    "CB_2P_PINS",
    "CB_3P_PINS",
    "CIRCUIT_SPACING",
    "CIRCUIT_SPACING_NARROW",
    "CIRCUIT_SPACING_WIDE",
    "COIL_PINS",
    "CONTACTOR_3P_PINS",
    "DEFAULT_POLE_SPACING",
    "GRID_SIZE",
    "NC_CONTACT_PINS",
    "NO_CONTACT_PINS",
    "PinPrefix",
    "SPACING_COMPACT",
    "SPACING_DEFAULT",
    "SPACING_NARROW",
    "SPACING_STANDARD",
    "StandardCircuitKeys",
    "StandardTags",
    "THERMAL_OVERLOAD_PINS",
    "WireLabels",
    # Utilities
    "GenerationState",
    "create_initial_state",
    "create_autonumberer",
    "get_tag_number",
    "next_tag",
    "next_terminal_pins",
    "export_terminal_list",
    "finalize_terminal_csv",
    "merge_terminal_csv",
    "apply_start_indices",
    "fixed_tag",
    "get_terminal_counter",
    "merge_terminals",
    "natural_sort_key",
    "set_tag_counter",
    "set_terminal_counter",
    "export_registry_to_csv",
    "get_registry",
    # Devices
    "InternalDevice",
    "CableData",
    "ConnectionRow",
    "ConnectorData",
    "DeviceCable",
    "DeviceEntry",
    "DeviceTemplate",
    "FieldDevice",
    "FixedPin",
    "PinDef",
    "PrefixedPin",
    "SequentialPin",
    "generate_field_connections",
    "Terminal",
    "BridgeRange",
    "ConnectionDef",
    "expand_range_to_pins",
    "generate_internal_connections_data",
    "get_connection_groups_for_terminal",
    "parse_terminal_pins_from_csv",
    "update_csv_with_internal_connections",
    # PLC
    "PlcDesignation",
    "PlcModuleType",
    "PlcRack",
    "extract_plc_connections_from_registry",
    "generate_plc_report_rows",
    "resolve_plc_references",
    # Exceptions
    "CircuitValidationError",
    "ComponentNotFoundError",
    "PortNotFoundError",
    "TagReuseError",
    "TerminalReuseError",
    "WireLabelMismatchError",
]
