"""Generate docs/data-model/ from the live schematika type graph.

Nodes are dataclasses, enums, ID scalars, protocols and the builder/hub classes.
Edges are typed references: dataclass fields, hub attributes and signatures,
inheritance, and module-level functions whose return type is built from their
parameter types. Function bodies are not analysed.

The whole output directory is generated; do not add hand-written files to it.
Needs every optional extra installed (`uv sync --all-extras`) so all modules import.

Usage:
    uv run python scripts/type_graph.py           # rewrite docs/data-model/
    uv run python scripts/type_graph.py --check   # exit 1 if the docs are stale
"""

import argparse
import ast
import dataclasses
import enum
import importlib
import inspect
import json
import pkgutil
import re
import sys
import textwrap
import typing
from collections import Counter, defaultdict, deque
from collections.abc import Callable, Iterable, Set
from pathlib import Path
from types import FunctionType

import schematika

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "docs" / "data-model"
CYTOSCAPE_JS = ROOT / "src" / "schematika" / "overview" / "assets" / "cytoscape.min.js"
HTML_TEMPLATE = Path(__file__).with_name("type_graph_template.html")

HUB_NAME = re.compile(r"(Builder|Harness|Catalog|Registry|Compiler)$|^Project$")
IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
STRUCTURAL = frozenset({"field", "holds", "inherits"})
TYPED_SURFACE = frozenset({"field", "holds", "inherits", "takes", "returns"})
PAGERANK_DAMPING = 0.85
PAGERANK_ITERATIONS = 100
PAGERANK_TOLERANCE = 1e-10
TOP_N = 15
LONG_LIST = 10
PKG_COLOR = {
    "core": "#7a8794",
    "catalog": "#e08a1e",
    "electrical": "#2f6fdb",
    "pcb": "#2a9d5f",
    "pid": "#17a2b8",
    "cable": "#8e5bd0",
    "overview": "#d6479b",
    "project": "#d1343b",
    "rendering": "#8c6d46",
}
FALLBACK_COLOR = "#999999"
# (root type id, depth) pairs drawn as containment diagrams in anatomy.md.
ANATOMY_ROOTS = (
    ("project.Project", 2),
    ("electrical.builder_models.BuildResult", 3),
    ("pcb.model.PCBBuildResult", 3),
    ("cable.result.CableBuildResult", 3),
)
NOTICE = (
    "> Generated by `scripts/type_graph.py` from the live code. Do not edit;"
    " regenerate with `just type-graph`."
)


@dataclasses.dataclass(frozen=True)
class Node:
    """One class in the graph, with its structural metrics."""

    id: str
    name: str
    package: str
    module: str
    kind: str
    frozen: bool
    doc: str
    fields: tuple[tuple[str, str], ...]
    fan_in: int = 0
    fan_out: int = 0
    dependents: int = 0
    dependencies: int = 0
    pagerank: float = 0.0
    kcore: int = 0


@dataclasses.dataclass(frozen=True)
class Edge:
    """`src` uses `dst`; `parts` are sorted (kind, name-of-field-or-function) pairs."""

    src: str
    dst: str
    parts: tuple[tuple[str, str], ...]

    @property
    def kinds(self) -> tuple[str, ...]:
        """Distinct relation kinds, sorted."""
        return tuple(sorted({kind for kind, _ in self.parts}))

    def names(self, kinds: Set[str] | None = None) -> tuple[str, ...]:
        """Field/method/function names behind this edge, optionally for some kinds."""
        return tuple(
            sorted({n for k, n in self.parts if n and (kinds is None or k in kinds)})
        )


@dataclasses.dataclass(frozen=True)
class Graph:
    """Nodes, edges and adjacency, plus hub attributes with no resolvable type."""

    nodes: dict[str, Node]
    edges: tuple[Edge, ...]
    untyped: dict[str, tuple[str, ...]]
    out: dict[str, tuple[Edge, ...]]
    inc: dict[str, tuple[Edge, ...]]


@dataclasses.dataclass(frozen=True)
class Index:
    """Discovered classes and a simple-name lookup used to resolve annotations."""

    classes: dict[str, type]
    by_simple: dict[str, list[str]]

    def resolve(self, names: set[str], own: str, module: str) -> set[str]:
        """Map annotation identifiers to node ids, preferring module scope."""
        mod = importlib.import_module(module)
        found: set[str] = set()
        for name in names:
            obj = getattr(mod, name, None)
            if isinstance(obj, type) and _qn(obj) in self.classes:
                found.add(_qn(obj))
                continue
            cands = self.by_simple.get(name, [])
            if len(cands) == 1:
                found.add(cands[0])
            elif cands:
                same = [c for c in cands if _package(c) == _package(own)]
                if len(same) == 1:
                    found.add(same[0])
        found.discard(own)
        return found


def _qn(cls: type) -> str:
    return f"{cls.__module__}.{cls.__qualname__}".removeprefix("schematika.")


def _package(node_id: str) -> str:
    return node_id.split(".")[0]


def _kind(cls: type) -> str | None:
    checks = (
        ("dataclass", dataclasses.is_dataclass(cls)),
        ("enum", issubclass(cls, enum.Enum)),
        (None, issubclass(cls, BaseException)),
        ("protocol", getattr(cls, "_is_protocol", False)),
        ("namedtuple", issubclass(cls, tuple) and hasattr(cls, "_fields")),
        ("scalar", issubclass(cls, str | int | float)),
        ("hub", bool(HUB_NAME.search(cls.__name__))),
    )
    return next((name for name, hit in checks if hit), None)


def _annotation_names(ann: object) -> set[str]:
    out: set[str] = set()

    def walk(tp: object) -> None:
        if isinstance(tp, str):
            out.update(IDENT.findall(tp))
        elif isinstance(tp, typing.ForwardRef):
            out.update(IDENT.findall(tp.__forward_arg__))
        elif isinstance(tp, type):
            out.add(tp.__name__)
        else:
            for arg in typing.get_args(tp):
                walk(arg)

    walk(ann)
    return out


def _annotation_text(ann: object) -> str:
    if isinstance(ann, str):
        return ann
    if isinstance(ann, type):
        return ann.__name__
    return re.sub(r"\b[\w]+\.(?=[A-Za-z_])", "", repr(ann))


def discover() -> tuple[Index, list[tuple[str, FunctionType]]]:
    """Import every module (except `__main__`s) and collect classes and functions."""
    names = sorted(
        m.name for m in pkgutil.walk_packages(schematika.__path__, "schematika.")
    )
    classes: dict[str, type] = {}
    funcs: list[tuple[str, FunctionType]] = []
    for name in names:
        if name.endswith(".__main__"):  # mcp/__main__ starts a stdio server on import
            continue
        mod = importlib.import_module(name)
        for obj in vars(mod).values():
            if isinstance(obj, type) and obj.__module__ == name and _kind(obj):
                classes[_qn(obj)] = obj
            elif (
                inspect.isfunction(obj)
                and obj.__module__ == name
                and not obj.__name__.startswith("_")
            ):
                funcs.append((name, obj))
    by_simple: dict[str, list[str]] = defaultdict(list)
    for node_id, cls in classes.items():
        by_simple[cls.__name__].append(node_id)
    return Index(classes, dict(by_simple)), funcs


def _is_self_attr(target: ast.expr) -> bool:
    return (
        isinstance(target, ast.Attribute)
        and isinstance(target.value, ast.Name)
        and target.value.id == "self"
    )


def _hub_edges(
    index: Index, node_id: str, cls: type, add: Callable[[str, str, str, str], None]
) -> list[str]:
    """Record a hub's attribute and signature edges; return its untyped attributes."""
    untyped: list[str] = []
    module = cls.__module__
    tree = ast.parse(textwrap.dedent(inspect.getsource(cls)))
    class_level = {id(n) for n in ast.iter_child_nodes(tree.body[0])}
    for node in ast.walk(tree):
        if not isinstance(node, ast.AnnAssign):
            continue
        target = node.target
        if id(node) not in class_level and not _is_self_attr(target):
            continue  # an annotated local variable, not state
        via = target.attr if isinstance(target, ast.Attribute) else ast.unparse(target)
        text = ast.unparse(node.annotation)
        dsts = index.resolve(set(IDENT.findall(text)), node_id, module)
        for dst in dsts:
            add(node_id, dst, "holds", via)
        if not dsts and (
            "Any" in text or "tuple[str" in text or text.startswith("list")
        ):
            untyped.append(f"{via}: {text}")
    for name, fn in cls.__dict__.items():
        fn = fn.__func__ if isinstance(fn, staticmethod | classmethod) else fn
        if not inspect.isfunction(fn) or (name.startswith("_") and name != "__init__"):
            continue
        for arg, ann in fn.__annotations__.items():
            kind = "returns" if arg == "return" else "takes"
            for dst in index.resolve(_annotation_names(ann), node_id, module):
                add(node_id, dst, kind, name)
    return untyped


def _collect_edges(
    index: Index, funcs: list[tuple[str, FunctionType]]
) -> tuple[dict[tuple[str, str], set[tuple[str, str]]], dict[str, tuple[str, ...]]]:
    raw: dict[tuple[str, str], set[tuple[str, str]]] = defaultdict(set)

    def add(src: str, dst: str, kind: str, via: str) -> None:
        raw[(src, dst)].add((kind, via))

    untyped: dict[str, tuple[str, ...]] = {}
    for node_id, cls in index.classes.items():
        kind = _kind(cls)
        if kind == "dataclass":
            for f in dataclasses.fields(cls):
                for dst in index.resolve(
                    _annotation_names(f.type), node_id, cls.__module__
                ):
                    add(node_id, dst, "field", f.name)
        for base in cls.__bases__:
            if base is not object and _qn(base) in index.classes:
                add(node_id, _qn(base), "inherits", "")
        if kind == "hub":
            found = _hub_edges(index, node_id, cls, add)
            if found:
                untyped[node_id] = tuple(found)
    for module, fn in funcs:
        own = module.removeprefix("schematika.") + ".<fn>"
        anns = getattr(fn, "__annotations__", {})
        returns = index.resolve(_annotation_names(anns.get("return")), own, module)
        params: set[str] = set()
        for arg, ann in anns.items():
            if arg != "return":
                params |= index.resolve(_annotation_names(ann), own, module)
        for ret in returns:
            for param in params - {ret}:
                add(ret, param, "flow", fn.__name__)
    return raw, untyped


def _node_fields(cls: type) -> tuple[tuple[str, str], ...]:
    if dataclasses.is_dataclass(cls):
        return tuple(
            (f.name, _annotation_text(f.type)) for f in dataclasses.fields(cls)
        )
    if issubclass(cls, enum.Enum):
        return tuple((m.name, repr(m.value)) for m in cls)
    return ()


def pagerank(ids: list[str], out: dict[str, list[str]]) -> dict[str, float]:
    """PageRank where rank flows to the types a type uses, so foundations rank high."""
    n = len(ids)
    rank = dict.fromkeys(ids, 1 / n)
    for _ in range(PAGERANK_ITERATIONS):
        dangling = sum(rank[i] for i in ids if not out[i])
        base = (1 - PAGERANK_DAMPING) / n + PAGERANK_DAMPING * dangling / n
        new = dict.fromkeys(ids, base)
        for i in ids:
            for j in out[i]:
                new[j] += PAGERANK_DAMPING * rank[i] / len(out[i])
        delta = sum(abs(new[i] - rank[i]) for i in ids)
        rank = new
        if delta < n * PAGERANK_TOLERANCE:
            break
    return rank


def core_numbers(adj: dict[str, set[str]]) -> dict[str, int]:
    """k-core number of every node of an undirected graph (peel min-degree first)."""
    degree = {i: len(js) for i, js in adj.items()}
    remaining = set(adj)
    core: dict[str, int] = {}
    k = 0
    while remaining:
        i = min(remaining, key=lambda x: (degree[x], x))
        k = max(k, degree[i])
        core[i] = k
        remaining.remove(i)
        for j in adj[i] & remaining:
            degree[j] -= 1
    return core


def _reach(start: str, adj: dict[str, list[str]]) -> set[str]:
    seen: set[str] = set()
    queue = deque([start])
    while queue:
        for nxt in adj[queue.popleft()]:
            if nxt not in seen and nxt != start:
                seen.add(nxt)
                queue.append(nxt)
    return seen


def build_graph() -> Graph:
    """Introspect the package and compute the graph with centrality metrics."""
    index, funcs = discover()
    raw, untyped = _collect_edges(index, funcs)
    edges = tuple(
        Edge(src, dst, tuple(sorted(parts)))
        for (src, dst), parts in sorted(raw.items())
    )
    ids = sorted(index.classes)
    typed = [e for e in edges if TYPED_SURFACE & set(e.kinds)]
    out_ids = {i: [e.dst for e in typed if e.src == i] for i in ids}
    in_ids = {i: [e.src for e in typed if e.dst == i] for i in ids}
    undirected = {i: (set(out_ids[i]) | set(in_ids[i])) - {i} for i in ids}
    rank = pagerank(ids, out_ids)
    cores = core_numbers(undirected)
    nodes: dict[str, Node] = {}
    for i in ids:
        cls = index.classes[i]
        kind = _kind(cls) or ""
        frozen = kind == "dataclass" and vars(cls)["__dataclass_params__"].frozen
        nodes[i] = Node(
            id=i,
            name=cls.__name__,
            package=_package(i),
            module=i.rsplit(".", 1)[0],
            kind=kind,
            frozen=frozen,
            doc=(inspect.getdoc(cls) or "").split("\n")[0][:140],
            fields=_node_fields(cls),
            fan_in=len(in_ids[i]),
            fan_out=len(out_ids[i]),
            dependents=len(_reach(i, in_ids)),
            dependencies=len(_reach(i, out_ids)),
            pagerank=round(rank[i], 6),
            kcore=cores[i],
        )
    out = {i: tuple(e for e in edges if e.src == i) for i in ids}
    inc = {i: tuple(e for e in edges if e.dst == i) for i in ids}
    return Graph(nodes, edges, untyped, out, inc)


# --- rendering helpers ------------------------------------------------------------


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _code(text: str) -> str:
    return f"`{_cell(text)}`" if text else ""


def _table(header: tuple[str, ...], rows: Iterable[tuple[str, ...]]) -> list[str]:
    lines = [f"| {' | '.join(header)} |", f"|{'---|' * len(header)}"]
    lines.extend(f"| {' | '.join(row)} |" for row in rows)
    return lines


def _tint(hex_color: str) -> str:
    rgb = [int(hex_color[i : i + 2], 16) for i in (1, 3, 5)]
    return "#" + "".join(f"{round(c + (255 - c) * 0.82):02x}" for c in rgb)


def _mid(node_id: str) -> str:
    return "n_" + re.sub(r"\W", "_", node_id)


def _mermaid(
    nodes: Iterable[Node], edges: Iterable[Edge], *, direction: str, labels: bool
) -> list[str]:
    nodes = sorted(nodes, key=lambda n: n.id)
    dupes = {name for name, c in Counter(n.name for n in nodes).items() if c > 1}
    lines = ["```mermaid", f"flowchart {direction}"]
    for n in nodes:
        text = f"{n.name}<br/>{n.module}" if n.name in dupes else n.name
        shape = f'(["{text}"])' if n.kind == "hub" else f'["{text}"]'
        lines.append(f"    {_mid(n.id)}{shape}:::pkg_{n.package}")
    for e in edges:
        label = e.names(STRUCTURAL)[:1] if labels else ()
        arrow = f"-->|{label[0]}|" if label else "-->"
        if not STRUCTURAL & set(e.kinds):
            arrow = "-.->"
        lines.append(f"    {_mid(e.src)} {arrow} {_mid(e.dst)}")
    for pkg in sorted({n.package for n in nodes}):
        color = PKG_COLOR.get(pkg, FALLBACK_COLOR)
        lines.append(
            f"    classDef pkg_{pkg} fill:{_tint(color)},stroke:{color},color:#1d1f21"
        )
    lines.append("```")
    return lines


def _names(graph: Graph, ids: Iterable[str], limit: int = 12) -> str:
    names = sorted({graph.nodes[i].name for i in ids})
    extra = f", +{len(names) - limit} more" if len(names) > limit else ""
    return ", ".join(f"`{n}`" for n in names[:limit]) + extra


def _details(summary: str, body: list[str]) -> list[str]:
    return ["<details>", f"<summary>{summary}</summary>", "", *body, "", "</details>"]


def _package_edges(graph: Graph) -> Counter[tuple[str, str]]:
    counts: Counter[tuple[str, str]] = Counter()
    for e in graph.edges:
        src, dst = graph.nodes[e.src].package, graph.nodes[e.dst].package
        if src != dst:
            counts[(src, dst)] += 1
    return counts


def _packages(graph: Graph) -> dict[str, list[Node]]:
    grouped: dict[str, list[Node]] = defaultdict(list)
    for n in graph.nodes.values():
        grouped[n.package].append(n)
    return dict(sorted(grouped.items()))


# --- pages ---------------------------------------------------------------------------


def _backbone_section(graph: Graph) -> list[str]:
    project = graph.nodes["project.Project"]
    results = [
        n
        for n in graph.nodes.values()
        if n.kind == "dataclass" and n.name.endswith("BuildResult")
    ]
    reach: dict[str, list[str]] = {
        i: [e.dst for e in graph.out[i] if TYPED_SURFACE & set(e.kinds)]
        for i in graph.nodes
    }
    reachable = _reach(project.id, reach)
    direct = {e.dst: e.kinds for e in graph.out[project.id]}
    rows = []
    for r in results:
        built = sorted(
            {
                f"{graph.nodes[e.src].name}.{n}"
                for e in graph.inc[r.id]
                for n in e.names({"returns"})
            }
            | {f"{n}()" for e in graph.out[r.id] for n in e.names({"flow"})}
        )
        kinds = direct.get(r.id, ())
        if "holds" in kinds:
            link = "attribute"
        elif kinds:
            link = "signature only"
        else:
            link = "indirect" if r.id in reachable else "none"
        rows.append(
            (f"`{r.name}`", r.package, ", ".join(_code(b) for b in built) or "-", link)
        )
    result_ids = {n.id for n in results}
    shared = [
        e
        for e in graph.edges
        if e.src in result_ids and e.dst in result_ids and "inherits" in e.kinds
    ]
    catalog = sorted(n.id for n in graph.nodes.values() if n.package == "catalog")
    no_catalog = sorted(
        pkg
        for pkg, members in _packages(graph).items()
        if pkg != "catalog"
        and not any(e.dst in catalog for m in members for e in graph.out[m.id])
    )
    resolved = graph.nodes["catalog.result.ResolvedCatalog"]
    unused_ids = sorted(
        n.name for n in graph.nodes.values() if n.kind == "scalar" and not n.fan_in
    )
    lines = [
        "## The backbone, as typed in the code",
        "",
        "The intended flow is `catalog` -> builders -> `*BuildResult` -> `Project`. "
        "This section checks how much of it is expressed in types "
        "(attributes and signatures only; function bodies are invisible here).",
        "",
        *_table(("Result type", "Package", "Built by", "Link from `Project`"), rows),
        "",
        f"- Shared base class or protocol among the {len(results)} "
        "`*BuildResult` types: " + ("yes" if shared else "**none**"),
        "- `ResolvedCatalog` is referenced by: "
        + _names(graph, (e.src for e in graph.inc[resolved.id])),
        "- Packages with no typed reference to `catalog`: "
        + (", ".join(f"`{p}`" for p in no_catalog) or "none"),
        "- Exported ID types nothing references: "
        + (", ".join(f"`{n}`" for n in unused_ids) or "none"),
        "",
        "### Hub attributes with no resolvable type",
        "",
        "Attributes annotated as a bare `list`, `Any` or tuples of `str` "
        "(a heuristic, so read it as a lead, not a verdict).",
        "",
    ]
    for hub_id, attrs in sorted(graph.untyped.items()):
        body = [f"- `{a}`" for a in attrs]
        name = graph.nodes[hub_id].name
        lines.extend(
            _details(f"<code>{name}</code>: {len(attrs)}", body)
            if len(attrs) > LONG_LIST
            else [f"**`{name}`: {len(attrs)}**", "", *body]
        )
        lines.append("")
    return lines


def render_index(graph: Graph) -> str:
    """Render docs/data-model/index.md."""
    kinds = Counter(n.kind for n in graph.nodes.values())
    frozen = sum(n.frozen for n in graph.nodes.values())
    mutable = kinds["dataclass"] - frozen
    rows = [
        (
            f"[`{pkg}`](packages/{pkg}.md)",
            str(len(ns)),
            str(sum(n.frozen for n in ns)),
            str(sum(n.kind == "dataclass" and not n.frozen for n in ns)),
        )
        for pkg, ns in _packages(graph).items()
    ]
    pkg_edges = _package_edges(graph)
    layer = ["```mermaid", "flowchart LR"]
    for pkg, ns in _packages(graph).items():
        layer.append(f'    {pkg}["{pkg} ({len(ns)})"]:::pkg_{pkg}')
    layer.extend(f"    {s} -->|{c}| {d}" for (s, d), c in sorted(pkg_edges.items()))
    for pkg in _packages(graph):
        color = PKG_COLOR.get(pkg, FALLBACK_COLOR)
        layer.append(
            f"    classDef pkg_{pkg} fill:{_tint(color)},stroke:{color},color:#1d1f21"
        )
    layer.append("```")
    centre = sorted(graph.nodes.values(), key=lambda n: (-n.pagerank, n.id))[:TOP_N]
    isolated = [
        n for n in graph.nodes.values() if not graph.out[n.id] and not graph.inc[n.id]
    ]
    iso_by_pkg = defaultdict(list)
    for n in isolated:
        iso_by_pkg[n.package].append(n.name)
    lines = [
        "# Schematika data model",
        "",
        NOTICE,
        "",
        f"{len(graph.nodes)} types ({kinds['dataclass']} dataclasses: {frozen} frozen, "
        f"{mutable} mutable; {kinds['hub']} builder/registry/`Project` classes; "
        f"{kinds['scalar']} ID scalars; {kinds['enum']} enums; "
        f"{kinds['protocol']} protocols; {kinds['namedtuple']} namedtuple) "
        f"and {len(graph.edges)} typed relations.",
        "",
        "- [Interactive graph](type_graph.html): rings from centre to periphery, "
        "click any type for what it uses and what uses it.",
        "- [Anatomy](anatomy.md): what `Project`, `BuildResult`, `PCBBuildResult` and "
        "`CableBuildResult` contain, recursively.",
        "- Per-package pages with a data dictionary of every type: see below.",
        "",
        'An edge `A -> B` means "A uses B". Relation kinds: `field` (dataclass field), '
        "`holds` (hub attribute), `inherits`, `returns`/`takes` (hub method "
        "signatures), "
        "`flow` (a module-level function returns A built from B).",
        "",
        "## Packages",
        "",
        *_table(
            ("Package", "Types", "Frozen dataclasses", "Mutable dataclasses"), rows
        ),
        "",
        "## Layer map",
        "",
        "Arrows are counts of typed references between packages (all relation "
        "kinds). References are resolved by name from annotations, so an arrow can "
        "come from a type-only import and is not always a runtime import.",
        "",
        *layer,
        "",
        *_table(
            ("From", "To", "References"),
            [
                (f"`{s}`", f"`{d}`", str(c))
                for (s, d), c in sorted(
                    pkg_edges.items(), key=lambda kv: (-kv[1], kv[0])
                )
            ],
        ),
        "",
        "## Centre of the graph",
        "",
        'Ranked by PageRank over "uses" edges: a type ranks high when many important '
        "types depend on it. *Blast radius* is the number of types that transitively "
        "depend on it. Only `field`, `holds`, `inherits`, `takes` and `returns` edges "
        "count; `flow` edges are shown but not counted, because a factory function "
        "does not make its return type depend on its argument types.",
        "",
        *_table(
            ("Type", "Package", "Kind", "Direct users", "Blast radius", "Uses"),
            [
                (
                    f"`{n.name}`",
                    n.package,
                    n.kind,
                    str(n.fan_in),
                    str(n.dependents),
                    str(n.fan_out),
                )
                for n in centre
            ],
        ),
        "",
        *_backbone_section(graph),
        "## Isolated types",
        "",
        f"{len(isolated)} types have no typed relation to any other type in this graph "
        "(they may still be used inside function bodies).",
        "",
        *[
            f"- `{pkg}`: {', '.join(f'`{n}`' for n in sorted(names))}"
            for pkg, names in sorted(iso_by_pkg.items())
        ],
        "",
    ]
    return "\n".join(lines)


def render_anatomy(graph: Graph) -> str:
    """Render docs/data-model/anatomy.md: containment diagrams from chosen roots."""
    lines = [
        "# Anatomy",
        "",
        NOTICE,
        "",
        "Each diagram starts at one type and follows `field`, `holds` and `inherits` "
        "edges down to a fixed depth: what the type contains, recursively. "
        "Edge labels are field or attribute names. "
        "Hubs (builders, `Project`) are stadium-shaped.",
        "",
    ]
    for root, depth in ANATOMY_ROOTS:
        adj = {
            i: [e.dst for e in graph.out[i] if STRUCTURAL & set(e.kinds)]
            for i in graph.nodes
        }
        seen = {root}
        frontier = [root]
        for _ in range(depth):
            frontier = sorted({d for i in frontier for d in adj[i]} - seen)
            seen.update(frontier)
        edges = [
            e
            for e in graph.edges
            if e.src in seen and e.dst in seen and STRUCTURAL & set(e.kinds)
        ]
        lines += [
            f"## `{graph.nodes[root].name}`",
            "",
            f"{len(seen)} types within depth {depth} of `{root}`.",
            "",
            *_mermaid(
                (graph.nodes[i] for i in seen), edges, direction="LR", labels=True
            ),
            "",
        ]
    return "\n".join(lines)


def _type_section(graph: Graph, n: Node) -> list[str]:
    badge = n.kind + (
        ", frozen" if n.frozen else ", mutable" if n.kind == "dataclass" else ""
    )
    lines = [f"### {n.name}", "", f"`{n.module}` - {badge}", ""]
    if n.doc:
        lines += [n.doc, ""]
    if n.fields:
        header = ("Member", "Value") if n.kind == "enum" else ("Field", "Type")
        lines += [*_table(header, [(f"`{f}`", _code(t)) for f, t in n.fields]), ""]
    elif n.kind == "hub":
        rows = [
            (
                f"`{graph.nodes[e.dst].name}`",
                ", ".join(e.kinds),
                ", ".join(_code(v) for v in e.names()),
            )
            for e in graph.out[n.id]
        ]
        lines += [*_table(("Uses", "Kind", "Via"), rows), ""] if rows else []
    if graph.inc[n.id]:
        lines += [f"Used by: {_names(graph, (e.src for e in graph.inc[n.id]))}", ""]
    return lines


def render_package(graph: Graph, pkg: str, members: list[Node]) -> str:
    """Render docs/data-model/packages/<pkg>.md."""
    ids = {n.id for n in members}
    inner = [
        e
        for e in graph.edges
        if e.src in ids and e.dst in ids and STRUCTURAL & set(e.kinds)
    ]
    linked = {e.src for e in inner} | {e.dst for e in inner}
    outward: dict[str, set[str]] = defaultdict(set)
    inward: dict[str, set[str]] = defaultdict(set)
    for e in graph.edges:
        s, d = graph.nodes[e.src], graph.nodes[e.dst]
        if s.package == pkg and d.package != pkg:
            outward[d.package].add(d.name)
        if d.package == pkg and s.package != pkg:
            inward[s.package].add(s.name)
    lines = [f"# Package `{pkg}`", "", NOTICE, "", f"{len(members)} types.", ""]
    if inner:
        lines += [
            "## Structure inside the package",
            "",
            "Fields, hub attributes and inheritance between this package's own types.",
            "",
            *_mermaid(
                (graph.nodes[i] for i in linked), inner, direction="LR", labels=False
            ),
            "",
        ]
    lines += ["## Cross-package references", ""]
    for title, table in (("Uses", outward), ("Used by", inward)):
        rows = [
            (f"`{p}`", ", ".join(f"`{x}`" for x in sorted(v)))
            for p, v in sorted(table.items())
        ]
        lines += [
            f"**{title}**",
            "",
            *(_table(("Package", "Types"), rows) if rows else ["none"]),
            "",
        ]
    lines += ["## Types", ""]
    for n in sorted(members, key=lambda m: (m.module, m.name)):
        lines += _type_section(graph, n)
    return "\n".join(lines)


def render_html(graph: Graph) -> str:
    """Render the self-contained interactive page (inlines the bundled Cytoscape.js)."""
    data = {
        "nodes": [
            {
                "id": n.id,
                "name": n.name,
                "package": n.package,
                "module": n.module,
                "kind": n.kind,
                "frozen": n.frozen,
                "n_fields": len(n.fields) if n.kind == "dataclass" else 0,
                "doc": n.doc,
                "fan_in": n.fan_in,
                "fan_out": n.fan_out,
                "pagerank": n.pagerank,
                "kcore": n.kcore,
                "dependents": n.dependents,
                "dependencies": n.dependencies,
            }
            for n in graph.nodes.values()
        ],
        "edges": [
            {
                "source": e.src,
                "target": e.dst,
                "kinds": list(e.kinds),
                "via": list(e.names())[:6],
            }
            for e in graph.edges
        ],
    }
    page = HTML_TEMPLATE.read_text(encoding="utf-8")
    page = page.replace("__CYTOSCAPE__", CYTOSCAPE_JS.read_text(encoding="utf-8"))
    return page.replace("__DATA__", json.dumps(data, sort_keys=True))


def render_all(graph: Graph) -> dict[Path, str]:
    """Every generated file, keyed by absolute path."""
    files = {
        OUT_DIR / "index.md": render_index(graph),
        OUT_DIR / "anatomy.md": render_anatomy(graph),
        OUT_DIR / "type_graph.html": render_html(graph),
    }
    for pkg, members in _packages(graph).items():
        files[OUT_DIR / "packages" / f"{pkg}.md"] = render_package(graph, pkg, members)
    return {path: text.rstrip("\n") + "\n" for path, text in files.items()}


def find_stale(out_dir: Path, files: dict[Path, str]) -> list[Path]:
    """Paths that are missing, differ from `files`, or are orphans under `out_dir`."""
    stale = [
        p for p, text in files.items() if not p.exists() or p.read_text("utf-8") != text
    ]
    existing = (
        {p for p in out_dir.rglob("*") if p.is_file()} if out_dir.exists() else set()
    )
    return sorted(set(stale) | (existing - set(files)))


def main(argv: list[str] | None = None) -> int:
    """Write the docs, or with --check report which are stale."""
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if docs are stale")
    args = parser.parse_args(argv)
    files = render_all(build_graph())
    stale = find_stale(OUT_DIR, files)
    if args.check:
        for path in stale:
            sys.stdout.write(f"stale: {path.relative_to(ROOT)}\n")
        return 1 if stale else 0
    for path in stale:
        if path in files:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(files[path], encoding="utf-8", newline="\n")
        else:
            path.unlink()
    sys.stdout.write(
        f"wrote {len(stale)} of {len(files)} files under {OUT_DIR.relative_to(ROOT)}\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
