"""Block diagram module for system-level cable interconnection diagrams."""

from schematika.block.constants import (
    BLOCK_DEFAULT_HEIGHT,
    BLOCK_GAP,
    BLOCK_LABEL_SIZE,
    BLOCK_MIN_WIDTH,
    BLOCK_STROKE_WIDTH,
    CABLE_BUNDLE_SPACING,
    CABLE_COLOR_AC_POWER,
    CABLE_COLOR_DC_CONTROL,
    CABLE_COLOR_ETHERNET,
    CABLE_COLOR_SIGNAL,
    CABLE_ETHERNET_DASH,
    CABLE_LABEL_OFFSET,
    CABLE_WEIGHT_CONTROL,
    CABLE_WEIGHT_ETHERNET,
    CABLE_WEIGHT_POWER,
    CABLE_WEIGHT_SIGNAL,
    CONTAINER_PADDING,
    GRID_SIZE,
    LEGEND_ENTRY_HEIGHT,
    LEGEND_LINE_SAMPLE_LENGTH,
    NOTE_TEXT_SIZE,
    TAG_BOX_PADDING,
    TAG_LABEL_SIZE,
)
from schematika.block.diagram import BlockDiagram
from schematika.block.model import (
    AC_POWER,
    CABLE_TYPE_STYLES,
    DASHED,
    DC_CONTROL,
    ETHERNET,
    SIGNAL_CABLE,
    SOLID,
    Block,
    BlockStyle,
    Cable,
    CableStyle,
    MirroredBlock,
    Placement,
)
from schematika.block.validation import validate_block_diagram
from schematika.core.validation import ValidationResult

__all__ = [
    "AC_POWER",
    "BLOCK_DEFAULT_HEIGHT",
    "BLOCK_GAP",
    "BLOCK_LABEL_SIZE",
    "BLOCK_MIN_WIDTH",
    "BLOCK_STROKE_WIDTH",
    "Block",
    "BlockDiagram",
    "BlockStyle",
    "CABLE_BUNDLE_SPACING",
    "CABLE_COLOR_AC_POWER",
    "CABLE_COLOR_DC_CONTROL",
    "CABLE_COLOR_ETHERNET",
    "CABLE_COLOR_SIGNAL",
    "CABLE_ETHERNET_DASH",
    "CABLE_LABEL_OFFSET",
    "CABLE_TYPE_STYLES",
    "CABLE_WEIGHT_CONTROL",
    "CABLE_WEIGHT_ETHERNET",
    "CABLE_WEIGHT_POWER",
    "CABLE_WEIGHT_SIGNAL",
    "Cable",
    "CableStyle",
    "CONTAINER_PADDING",
    "DASHED",
    "DC_CONTROL",
    "ETHERNET",
    "GRID_SIZE",
    "LEGEND_ENTRY_HEIGHT",
    "LEGEND_LINE_SAMPLE_LENGTH",
    "MirroredBlock",
    "NOTE_TEXT_SIZE",
    "Placement",
    "SIGNAL_CABLE",
    "SOLID",
    "TAG_BOX_PADDING",
    "TAG_LABEL_SIZE",
    "ValidationResult",
    "validate_block_diagram",
]
