"""Block diagram module for system-level cable interconnection diagrams."""

from schematika.block.builder import BlockBuildResult, BlockBuilder
from schematika.block.connections import render_cable
from schematika.block.constants import (
    BLOCK_CABLE_CLEARANCE,
    BLOCK_DEFAULT_HEIGHT,
    BLOCK_DEFAULT_WIDTH,
    BLOCK_MIN_GAP,
    BLOCK_PORT_OFFSET,
    BLOCK_STROKE_WIDTH,
    BLOCK_TEXT_SIZE_CABLE,
    BLOCK_TEXT_SIZE_LABEL,
    BLOCK_TEXT_SIZE_NOTE,
    CABLE_COLOR_AC_POWER,
    CABLE_COLOR_DC_CONTROL,
    CABLE_COLOR_ETHERNET,
    CABLE_COLOR_SIGNAL,
    CABLE_ETHERNET_DASH,
    CABLE_WEIGHT_CONTROL,
    CABLE_WEIGHT_ETHERNET,
    CABLE_WEIGHT_POWER,
    CABLE_WEIGHT_SIGNAL,
    GRID_SIZE,
    LEGEND_ENTRY_HEIGHT,
    LEGEND_LINE_SAMPLE_LENGTH,
    LINE_WIDTH_THIN,
    TEXT_FONT_FAMILY,
    TEXT_SIZE_MAIN,
)
from schematika.block.diagram import (
    BlockDiagram,
    add_block,
    merge_block_diagrams,
    render_block_diagram,
)
from schematika.block.model import (
    AC_POWER,
    CABLE_TYPE_STYLES,
    DC_CONTROL,
    ETHERNET,
    SIGNAL_CABLE,
    BlockPort,
    CableStyle,
)
from schematika.block.symbols import block_symbol, legend_symbol
from schematika.block.templates import BlockTemplate, TemplateCable, TemplateBlock
from schematika.block.validation import validate_block_diagram
from schematika.core.validation import ValidationResult

__all__ = [
    "AC_POWER",
    "BLOCK_CABLE_CLEARANCE",
    "BLOCK_DEFAULT_HEIGHT",
    "BLOCK_DEFAULT_WIDTH",
    "BLOCK_MIN_GAP",
    "BLOCK_PORT_OFFSET",
    "BLOCK_STROKE_WIDTH",
    "BLOCK_TEXT_SIZE_CABLE",
    "BLOCK_TEXT_SIZE_LABEL",
    "BLOCK_TEXT_SIZE_NOTE",
    "BlockBuildResult",
    "BlockBuilder",
    "BlockDiagram",
    "BlockPort",
    "BlockTemplate",
    "CABLE_COLOR_AC_POWER",
    "CABLE_COLOR_DC_CONTROL",
    "CABLE_COLOR_ETHERNET",
    "CABLE_COLOR_SIGNAL",
    "CABLE_ETHERNET_DASH",
    "CABLE_TYPE_STYLES",
    "CABLE_WEIGHT_CONTROL",
    "CABLE_WEIGHT_ETHERNET",
    "CABLE_WEIGHT_POWER",
    "CABLE_WEIGHT_SIGNAL",
    "CableStyle",
    "DC_CONTROL",
    "ETHERNET",
    "GRID_SIZE",
    "LEGEND_ENTRY_HEIGHT",
    "LEGEND_LINE_SAMPLE_LENGTH",
    "LINE_WIDTH_THIN",
    "SIGNAL_CABLE",
    "TEXT_FONT_FAMILY",
    "TEXT_SIZE_MAIN",
    "TemplateCable",
    "TemplateBlock",
    "ValidationResult",
    "add_block",
    "block_symbol",
    "legend_symbol",
    "merge_block_diagrams",
    "render_block_diagram",
    "render_cable",
    "validate_block_diagram",
]
